import React, { useEffect, useState, useRef } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ROUTES } from '../../utils/constants';
import LoadingSpinner from '../../components/LoadingSpinner/LoadingSpinner';
import { Lightbulb, CheckCircle, AlertTriangle, Target, Briefcase, Award, TrendingUp, TrendingDown, Eye, ArrowRight } from 'lucide-react';

const ResumeAnalysis = () => {
  const [data, setData] = useState(null);
  const navigate = useNavigate();
  const circleRef = useRef(null);

  useEffect(() => {
    const stored = sessionStorage.getItem('currentAnalysis');
    if (stored) {
      setData(JSON.parse(stored));
    } else {
      navigate(ROUTES.UPLOAD);
    }
  }, [navigate]);

  useEffect(() => {
    if (data && data.analysis && circleRef.current) {
      const score = data.analysis.resume_score || 0;
      const radius = 60;
      const circumference = 2 * Math.PI * radius;
      const offset = circumference - (score / 100) * circumference;
      
      circleRef.current.style.strokeDasharray = `${circumference} ${circumference}`;
      circleRef.current.style.strokeDashoffset = circumference;
      
      setTimeout(() => {
        circleRef.current.style.strokeDashoffset = offset;
        if (score >= 80) circleRef.current.style.stroke = '#10b981'; // emerald-500
        else if (score >= 60) circleRef.current.style.stroke = '#f59e0b'; // amber-500
        else circleRef.current.style.stroke = '#ef4444'; // red-500
      }, 100);
    }
  }, [data]);

  if (!data || !data.analysis) return <LoadingSpinner text="Loading AI Analysis..." />;

  const { analysis } = data;
  const quotaWarning = analysis._quota_warning || null;

  const getScoreColorClass = (score) => {
    if (score >= 80) return 'text-emerald-400';
    if (score >= 60) return 'text-amber-400';
    return 'text-red-400';
  };

  const getScoreMessage = (score) => {
    if (score >= 80) return "Excellent! Your resume is highly optimized and competitive.";
    if (score >= 60) return "Good potential, but needs strategic improvements to stand out.";
    return "Needs significant changes. Strongly consider a complete rewrite.";
  };

  return (
    <div className="flex flex-col gap-8 max-w-4xl mx-auto pb-24 relative z-10">
      
      {/* Header */}
      <div className="text-center animate-fade-up stagger-1 mt-12 mb-4">
        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-white mb-4">
          Resume <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-violet-500">Analysis</span>
        </h1>
        <p className="text-lg text-slate-400 max-w-xl mx-auto">
          Here is what our AI uncovered in your resume profile.
        </p>
      </div>

      {/* Quota Warning Banner */}
      {quotaWarning && (
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl px-6 py-4 flex items-start gap-3 animate-fade-up">
          <span className="text-2xl shrink-0">⚠️</span>
          <div>
            <p className="text-amber-300 font-bold mb-1">AI Engine Temporarily Offline — Rule-Based Analysis</p>
            <p className="text-amber-400/80 text-sm leading-relaxed">
              The Gemini AI API has hit its daily free-tier limit (20 requests/day). 
              This analysis was generated by our local rule-based engine. 
              <strong className="text-amber-300"> Full AI analysis will resume automatically when quota resets.</strong> 
              To remove limits, add billing at <a href="https://aistudio.google.com" target="_blank" rel="noreferrer" className="underline">aistudio.google.com</a>.
            </p>
          </div>
        </div>
      )}

      {/* Score Card */}
      <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl shadow-2xl relative overflow-hidden animate-fade-up stagger-2 flex flex-col md:flex-row items-center gap-10">
        <div className="absolute top-0 left-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none"></div>
        
        {/* SVG Circular Progress */}
        <div className="relative w-40 h-40 flex items-center justify-center shrink-0">
          <svg className="w-full h-full transform -rotate-90" viewBox="0 0 140 140">
            <circle cx="70" cy="70" r="60" className="stroke-white/10" strokeWidth="12" fill="none" />
            <circle 
              ref={circleRef}
              cx="70" cy="70" r="60" 
              stroke="currentColor" 
              strokeWidth="12" 
              fill="none" 
              strokeLinecap="round"
              className="text-indigo-500 transition-all duration-1000 ease-out"
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className={`text-4xl font-black ${getScoreColorClass(analysis.resume_score)}`}>{analysis.resume_score}</span>
            <span className="text-xs text-slate-400 font-bold uppercase tracking-wider">/ 100</span>
          </div>
        </div>

        <div className="flex-1 text-center md:text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-indigo-400 text-xs font-bold uppercase tracking-wider mb-3">
            <Award className="w-4 h-4" /> Resume Impact Score
          </div>
          <h2 className={`text-2xl font-bold mb-3 ${getScoreColorClass(analysis.resume_score)}`}>
            {getScoreMessage(analysis.resume_score)}
          </h2>
          <p className="text-slate-400 leading-relaxed">
            Your score is calculated based on formatting, keyword density, structural clarity, and the strength of your action verbs. Let's break down exactly what you did right and what needs attention.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Summary Feedback */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl animate-fade-up stagger-3 group hover:bg-white/10 transition-colors">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/20 text-indigo-400 flex items-center justify-center">
              <Eye className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-white">Recruiter's Perspective</h3>
          </div>
          <p className="text-slate-300 leading-relaxed">{analysis.summary_feedback}</p>
        </div>

        {/* Future Proofing (AI Risk) */}
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl animate-fade-up stagger-4 group hover:bg-white/10 transition-colors">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-violet-500/20 text-violet-400 flex items-center justify-center">
              <Target className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-white">AI Replacement Risk</h3>
          </div>
          <p className="text-slate-300 leading-relaxed">{analysis.ai_replacement_risk}</p>
        </div>
      </div>

      {/* The Garbage Bin & Critical Mistakes */}
      <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl animate-fade-up stagger-5 overflow-hidden relative">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
          
          {/* Critical Mistakes */}
          <div>
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center">
                <AlertTriangle className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-white">Critical Mistakes</h3>
            </div>
            {analysis.critical_mistakes && analysis.critical_mistakes.length > 0 ? (
              <ul className="space-y-4">
                {analysis.critical_mistakes.map((item, idx) => (
                  <li key={idx} className="flex items-start gap-3">
                    <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
                    <span className="text-slate-300 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-emerald-400 flex items-center gap-2"><CheckCircle className="w-5 h-5"/> Your resume looks flawless in this area!</p>
            )}
          </div>

          {/* The Garbage Bin */}
          <div>
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-red-500/20 text-red-400 flex items-center justify-center">
                <TrendingDown className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-white">The "Garbage" Bin</h3>
            </div>
            <p className="text-slate-400 mb-4 text-sm">Remove these cliches, fluff words, and weak points immediately:</p>
            {analysis.garbage_to_remove && analysis.garbage_to_remove.length > 0 ? (
              <ul className="space-y-4">
                {analysis.garbage_to_remove.map((item, idx) => (
                  <li key={idx} className="flex items-start gap-3 p-3 rounded-xl bg-red-500/5 border border-red-500/10">
                    <span className="text-red-400 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-emerald-400 flex items-center gap-2"><CheckCircle className="w-5 h-5"/> No fluff found!</p>
            )}
          </div>

        </div>
      </div>

      {/* Immediate Job Matches */}
      {analysis.immediate_job_matches && analysis.immediate_job_matches.length > 0 && (
        <div className="bg-white/5 border border-white/10 rounded-3xl p-8 backdrop-blur-xl animate-fade-up stagger-6">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center">
              <Briefcase className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-white">Jobs You Can Apply For Right Now</h3>
          </div>
          <p className="text-slate-400 mb-6">Based on your exact skills, you are strongly qualified for these roles:</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {analysis.immediate_job_matches.map((job, idx) => (
              <div key={idx} className="px-5 py-4 rounded-xl bg-white/5 border border-white/10 text-slate-200 font-medium hover:border-emerald-500/50 transition-colors cursor-default flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0" />
                {job}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Next Steps CTA */}
      <div className="bg-gradient-to-br from-indigo-500/10 to-violet-500/10 border border-indigo-500/20 rounded-3xl p-10 text-center animate-fade-up stagger-6 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10"></div>
        <div className="relative z-10">
          <h3 className="text-2xl font-bold text-white mb-4">Ready to take the next step?</h3>
          <p className="text-slate-400 max-w-lg mx-auto mb-8">
            Your resume is analyzed. Now, let's see what jobs you match with, or dive deeper into your skill gaps.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Link to={ROUTES.SKILL_GAP} className="px-8 py-4 rounded-xl font-bold text-white bg-white/5 border border-white/10 hover:bg-white/10 transition-colors backdrop-blur-md">
              View Skill Gaps
            </Link>
            <Link to={ROUTES.JOB_MATCHING} className="group flex items-center justify-center gap-2 bg-white text-black font-bold py-4 px-8 rounded-xl transition-all hover:bg-slate-200 shadow-[0_0_20px_rgba(255,255,255,0.2)]">
              Find Matching Jobs <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </div>
      </div>

    </div>
  );
};

export default ResumeAnalysis;
