-- Seed jobs for AI Resume Analyzer Job Matching
INSERT INTO jobs (title, company, description, required_skills, created_at) VALUES
('Software Engineer', 'Google', 'Join the Search team to work on core ranking algorithms. You will build highly scalable and reliable services that serve billions of users. Experience with Java, Python, C++, distributed systems, and backend development is required.', 'Java, Python, C++, Distributed Systems, Algorithms, Data Structures', CURRENT_TIMESTAMP()),
('Frontend Developer', 'Netflix', 'Build the next generation user interface for the Netflix streaming client. You will craft high-performance web components using modern CSS, HTML5, React, and TypeScript. A strong eye for details, motion/animation, and UX is critical.', 'React, TypeScript, JavaScript, CSS, HTML5, Web Performance', CURRENT_TIMESTAMP()),
('Backend Engineer', 'Stripe', 'Work on financial infrastructure that powers modern online business. Build clean REST APIs, optimize PostgreSQL queries, design messaging systems using Kafka, and ensure 99.999% uptime. Experience with Java, Go, or Ruby on Rails.', 'Java, Go, REST APIs, PostgreSQL, Kafka, System Design', CURRENT_TIMESTAMP()),
('Full Stack Developer', 'Airbnb', 'Create end-to-end features for our host community. Build elegant React frontends and robust Node.js/GraphQL backend services. Ideal candidate has strong knowledge of full-stack patterns and cloud services like AWS.', 'React, Node.js, GraphQL, JavaScript, AWS, MongoDB', CURRENT_TIMESTAMP()),
('Data Scientist', 'Meta', 'Apply statistical modeling and machine learning to improve user engagement and ad performance. Build data pipelines in Spark, design A/B tests, and train PyTorch models. Proficiency in Python and SQL is essential.', 'Python, SQL, PyTorch, Machine Learning, Statistics, Spark, A/B Testing', CURRENT_TIMESTAMP()),
('DevOps Engineer', 'Amazon Web Services', 'Help scale and secure our infrastructure. Design CI/CD pipelines, manage Kubernetes clusters, automate configuration management, and optimize cloud spend. Expert in Docker, Kubernetes, Terraform, and AWS.', 'Docker, Kubernetes, Terraform, AWS, Bash, CI/CD', CURRENT_TIMESTAMP()),
('Mobile App Engineer (iOS)', 'Apple', 'Design and implement new features for core iOS system apps. Write clean, maintainable Swift and SwiftUI code. Collaborate with designers on animation and user experience. Understanding of CoreData and memory management is required.', 'Swift, SwiftUI, iOS SDK, CoreData, Git, Mobile Development', CURRENT_TIMESTAMP()),
('Product Manager', 'Microsoft', 'Lead a team of engineers and designers to define and deliver the roadmap for AI-driven office tools. Define metrics, gather customer feedback, and write specifications. Strong communication and analytical skills.', 'Product Management, Agile, SQL, Communication, Strategy', CURRENT_TIMESTAMP()),
('Security Engineer', 'Cloudflare', 'Protect our networks and customers from sophisticated DDoS attacks and security breaches. Perform penetration testing, implement cryptographic protocols, and analyze log data. Experience with Go, C, and network protocols.', 'Go, Networking, Cryptography, Penetration Testing, Linux', CURRENT_TIMESTAMP()),
('UI/UX Designer', 'Figma', 'Craft intuitive tools for creators worldwide. Design user flows, build high-fidelity interactive prototypes, and collaborate on the design system. Deep understanding of typography, spacing, CSS, and modern visual trends.', 'Figma, UI/UX Design, Prototyping, CSS, Interaction Design', CURRENT_TIMESTAMP());
