import React, { useState, useEffect, useRef } from 'react';
import api from '../../services/api';
import LoadingSpinner from '../../components/LoadingSpinner/LoadingSpinner';
import { Bot } from 'lucide-react';

const MockInterview = () => {
  const [setupMode, setSetupMode] = useState(true);
  const [skills, setSkills] = useState('');
  const [experience, setExperience] = useState('2 years');
  const [questions, setQuestions] = useState([]);
  const [currentQIdx, setCurrentQIdx] = useState(0);
  const [answer, setAnswer] = useState('');
  const [transcript, setTranscript] = useState([]);
  const [loading, setLoading] = useState(false);
  const [evaluating, setEvaluating] = useState(false);
  const [evaluation, setEvaluation] = useState(null);
  
  const messagesEndRef = useRef(null);

  useEffect(() => {
    // Try to pre-fill skills from session storage
    const stored = sessionStorage.getItem('currentAnalysis');
    if (stored) {
      const data = JSON.parse(stored);
      if (data.parsed_data?.skills) {
        setSkills(data.parsed_data.skills.slice(0, 5).join(', '));
      }
    }
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [transcript]);

  const handleStart = async (e) => {
    e.preventDefault();
    if (!skills) return;
    
    setLoading(true);
    try {
      const skillList = skills.split(',').map(s => s.trim());
      const response = await api.post('/api/interviews/generate-questions', { skills: skillList, experience });
      setQuestions(response.data.questions || []);
      setSetupMode(false);
    } catch (err) {
      console.error(err);
      alert('Failed to generate questions. Please check AI Service connection.');
    } finally {
      setLoading(false);
    }
  };

  const handleNextQuestion = () => {
    if (!answer.trim()) return;

    const newTranscript = [...transcript, { 
      question: questions[currentQIdx]?.question || '', 
      answer: answer 
    }];
    setTranscript(newTranscript);
    setAnswer('');

    if (currentQIdx < questions.length - 1) {
      setCurrentQIdx(currentQIdx + 1);
    } else {
      // Finished
      submitForEvaluation(newTranscript);
    }
  };

  const submitForEvaluation = async (finalTranscript) => {
    setEvaluating(true);
    try {
      const response = await api.post('/api/interviews/evaluate', { transcript: finalTranscript });
      setEvaluation(response.data);
    } catch (err) {
      console.error(err);
      alert('Failed to evaluate interview.');
    } finally {
      setEvaluating(false);
    }
  };

  if (setupMode) {
    return (
      <div className="flex-col gap-lg max-w-2xl mx-auto">
        <div className="text-center mb-md">
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1rem' }}>
            <Bot size={48} color="var(--color-primary)" />
          </div>
          <h1 className="section-title">AI Mock Interview</h1>
          <p className="text-muted">Prepare for your next technical interview with personalized questions generated by Gemini.</p>
        </div>

        <div className="card">
          <form onSubmit={handleStart} className="flex-col gap-md">
            <div className="form-group">
              <label className="form-label">Key Skills to Test (comma separated)</label>
              <input 
                type="text" 
                className="form-input" 
                placeholder="e.g. React, Java, Spring Boot, Microservices"
                value={skills}
                onChange={(e) => setSkills(e.target.value)}
                required
              />
            </div>
            
            <div className="form-group">
              <label className="form-label">Target Experience Level</label>
              <select 
                className="form-input"
                value={experience}
                onChange={(e) => setExperience(e.target.value)}
              >
                <option value="Entry Level (0-1 years)">Entry Level (0-1 years)</option>
                <option value="Junior (1-3 years)">Junior (1-3 years)</option>
                <option value="Mid-Level (3-5 years)">Mid-Level (3-5 years)</option>
                <option value="Senior (5+ years)">Senior (5+ years)</option>
              </select>
            </div>

            <button type="submit" className="btn btn-primary mt-sm" disabled={loading}>
              {loading ? 'Generating Scenario...' : 'Start Interview'}
            </button>
          </form>
        </div>
      </div>
    );
  }

  if (evaluating) {
    return <LoadingSpinner text="AI is evaluating your responses..." size="large" />;
  }

  if (evaluation) {
    return (
      <div className="flex-col gap-lg max-w-4xl mx-auto animate-fade-in">
        <h1 className="section-title text-center">Interview Feedback</h1>
        
        <div className="card text-center mb-lg">
          <h2 style={{ fontSize: '3rem', color: 'var(--color-primary)', marginBottom: '0.5rem' }}>{evaluation.score}/100</h2>
          <p className="text-muted">Overall Performance Score</p>
        </div>

        <div className="card">
          <h3 className="mb-md">Detailed Feedback</h3>
          <div className="prose text-muted" style={{ whiteSpace: 'pre-line', lineHeight: '1.8' }}>
            {evaluation.feedback}
          </div>
        </div>

        <button className="btn btn-secondary mx-auto mt-md" onClick={() => { setSetupMode(true); setEvaluation(null); setTranscript([]); setCurrentQIdx(0); }}>
          Start Another Interview
        </button>
      </div>
    );
  }

  return (
    <div className="flex-col gap-lg max-w-3xl mx-auto" style={{ height: 'calc(100vh - 120px)' }}>
      <div className="flex justify-between items-center pb-sm border-b" style={{ borderColor: 'var(--color-border-subtle)' }}>
        <h2>Mock Interview in Progress</h2>
        <span className="badge badge-primary">Question {currentQIdx + 1} of {questions.length}</span>
      </div>

      {/* Chat History */}
      <div className="flex-1 overflow-y-auto flex-col gap-md pr-sm" style={{ display: 'flex', flexDirection: 'column' }}>
        {transcript.map((item, idx) => (
          <React.Fragment key={idx}>
            <div className="chat-bubble chat-bubble-ai">
              <strong>Interviewer:</strong><br/>{item.question}
            </div>
            <div className="chat-bubble chat-bubble-user">
              <strong>You:</strong><br/>{item.answer}
            </div>
          </React.Fragment>
        ))}

        {/* Current Question */}
        <div className="chat-bubble chat-bubble-ai" style={{ border: '1px solid var(--color-primary)' }}>
          <strong>Interviewer:</strong><br/>{questions[currentQIdx]?.question}
        </div>
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="card" style={{ padding: '1rem', marginTop: 'auto' }}>
        <div className="form-group">
          <textarea 
            className="form-input" 
            style={{ minHeight: '100px' }}
            placeholder="Type your answer here... Be as detailed as possible."
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
          ></textarea>
        </div>
        <div className="flex justify-end mt-sm">
          <button className="btn btn-primary" onClick={handleNextQuestion} disabled={!answer.trim()}>
            {currentQIdx === questions.length - 1 ? 'Submit Interview' : 'Next Question'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default MockInterview;
